# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 616)
        MainWindow.setStyleSheet("color:black;\n"
"background:grey;")
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 12, 361, 211))
        self.calendarWidget.setStyleSheet("color:orange;\n"
"background:black;\n"
"border:3px dotted #ffffff; \n"
"border-radius: 10px; \n"
"font-size:8px; \n"
"font-weight:3000;\n"
"")
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(380, 10, 131, 51))
        self.start_btn.setStyleSheet("QPushButton {\n"
"     border:3px dashed #ffffff; \n"
"    border-radius: 12px; \n"
"    font-size:20px; \n"
"    font-weight:500;\n"
" } \n"
"QPushButton:pressed { \n"
"    background-color:#2C2D2C; \n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(380, 80, 131, 51))
        self.stop_btn.setStyleSheet("QPushButton {\n"
"     border:3px dashed #ffffff; \n"
"    border-radius: 12px; \n"
"    font-size:20px; \n"
"    font-weight:500;\n"
" } \n"
"QPushButton:pressed { \n"
"    background-color:#2C2D2C; \n"
"}")
        self.stop_btn.setObjectName("stop_btn")
        self.Autostart_btn = QtWidgets.QCheckBox(self.centralwidget)
        self.Autostart_btn.setGeometry(QtCore.QRect(380, 150, 131, 61))
        self.Autostart_btn.setStyleSheet("border:3px dashed #ffffff; \n"
"border-radius: 12px; \n"
"font-size:20px; \n"
"font-weight:500;\n"
"")
        self.Autostart_btn.setObjectName("Autostart_btn")
        self.video = QVideoWidget(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(10, 230, 521, 341))
        self.video.setStyleSheet("color:orange;\n"
"background:black;\n"
"border:3px dotted #ffffff; \n"
"border-radius: 10px; \n"
"font-size:8px; \n"
"font-weight:3000;\n"
"")
        self.video.setObjectName("video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 558, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.Autostart_btn.setText(_translate("MainWindow", "Autostart"))
from PyQt5.QtMultimediaWidgets import QVideoWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
